In [1]:
def test():
    print('test() for function')
    return
test()

test() for function


In [2]:
class demo:
    def test(self):
        print("test() for the class and method")
        return
    
obj = demo()
obj.test()

test() for the class and method


In [3]:
class demo1:
    def fact(self,n):
        #return the factorial
        return
    
p1 = demo1()
p1.fact(5)#120

In [4]:
class demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
            
        return fact
p1=demo1()
print(p1.fact(5))#120

120


In [8]:
class demo2:
    def __init__(self,p1,p2):
        self.p1=p2
        self.p2=p1
    def add(self,p1,p2):nnnv    
        return p1+p2
        
c1=demo2(10,20)
print(c1.add(100,200))

300


In [12]:
class person(object):
    def __init__(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isemployee(self):
        return False
    
class employee(person):
    def isemployee(self):
        return True
    
emp=person("anil")
print(emp.getname(),emp.isemployee())

emp1=employee("akhil")
print(emp1.getname(),emp1.isemployee())

anil False
akhil True


In [15]:
import numpy as np
lst =[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [16]:
lst = [1,2,3,4]
array = np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [18]:
lst=[1.65658,0,2,5,3,6,9,5]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(8,)
float64


In [19]:
a1=np.array([(1,2,3,),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [22]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [26]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a3=np.array([7,8,9])
print(np.dstack((a1,a2,a3)))

[[[1 4 7]
  [2 5 8]
  [3 6 9]]]


In [27]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [28]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [1]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [3]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [5]:
a1=np.array([(1,2,3),(4,5,6)])
print("slising column: ",a1[:,1])

slising column:  [2 5]


In [6]:
a1=np.array([(1,2,3),(4,5,6)])
print("slising column: ",a1[:,2])

slising column:  [3 6]


In [7]:
a1=np.array([(1,2,3),(4,5,6)])
print(" Row and column: ",a1[1,:2])


 Row and column:  [4 5]


In [9]:
a1=np.random.normal(5,1,10)
print(a1)
print("min values=",np.min(a1))
print("max values=",np.max(a1))
print("mean value=",np.mean(a1))
print("median value=",np.median(a1))

[5.00166121 7.04089584 7.90117083 6.23915642 3.01290451 4.66731166
 5.78108253 3.78399346 5.76290749 5.98267067]
min values= 3.0129045137868733
max values= 7.901170827194615
mean value= 5.517375461323206
median value= 5.771995012201284


In [11]:
c1 = np.array([1,2])
c2 = np.array([4,5])
np.dot(c1,c2)

14

In [12]:
c1 = np.array([(1,2),(3,4)])
c2 = np.array([(4,5),(1,2)])
np.dot(c1,c2)

array([[ 6,  9],
       [16, 23]])

In [20]:
import pandas as pd
dict = {"Name":["Anil","Akhil","Dinesh","Harsha","Ajay","Kranth"],
       "EmailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kran@gmail.com"],
        "MobileNumber":[999,888,777,888,777,999],
        "Address":["Vmd","Vmd","Vmd","Vmd","Vmd","Vmd"]}
b=pd.DataFrame(dict)
print(b)

     Name           EmailID  MobileNumber Address
0    Anil    anil@gmail.com           999     Vmd
1   Akhil   akhil@gmail.com           888     Vmd
2  Dinesh  dinesh@gmail.com           777     Vmd
3  Harsha  harsha@gmail.com           888     Vmd
4    Ajay    ajay@gmail.com           777     Vmd
5  Kranth    kran@gmail.com           999     Vmd
